<?php
if ( ! defined( 'ABSPATH' ) ) {
	if ( ! defined( 'WPINC' ) && ( ! defined( 'FF_USE_WP' ) || FF_USE_WP ) ) {
		exit;
	}
}
// phpcs:disable

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'la\\core\\' => array($vendorDir . '/flowflow/core/src'),
    'flow\\social\\' => array($vendorDir . '/flowflow/social/src/flow/social'),
    'flow\\' => array($baseDir . '/includes'),
    'Psr\\SimpleCache\\' => array($vendorDir . '/psr/simple-cache/src'),
    'Cake\\Utility\\' => array($vendorDir . '/cakephp/utility'),
    'Cake\\Core\\' => array($vendorDir . '/cakephp/core'),
    'Cake\\Cache\\' => array($vendorDir . '/cakephp/cache'),
);

// phpcs:enable
